name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of SONATE does this relate to?
      options:
        - Core (Trust Protocol, SONATE)
        - Detect (Drift, Emergence, Bedau)
        - Backend (API, Database)
        - Dashboard (Web UI)
        - Overseer (System Brain)
        - Documentation
        - DevOps (CI/CD, Deployment)
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples.
